namespace MarkLeaf.Commands;

public enum AppCommand
{
    NewDocument = 0x1001,
    NewWindow,
    OpenDocument,
    OpenDocumentReadOnly,
    OpenDocumentInNewWindow,
    OpenFolder,
    CloseFolder,
    SaveDocument,
    SaveDocumentAs,
    ExportPdf,
    ExportHtml,
    Print,
    Exit,
    OpenRecentWorkspace1,
    OpenRecentWorkspace2,
    OpenRecentWorkspace3,
    OpenRecentWorkspace4,
    OpenRecentWorkspace5,
    OpenRecentWorkspace6,
    OpenRecentWorkspace7,
    OpenRecentWorkspace8,
    OpenRecentFile1,
    OpenRecentFile2,
    OpenRecentFile3,
    OpenRecentFile4,
    OpenRecentFile5,
    OpenRecentFile6,
    OpenRecentFile7,
    OpenRecentFile8,
    RecoverUnsavedFiles,

    Undo = 0x1101,
    Redo,
    Cut,
    Copy,
    CopyMarkdown,
    CopyPlainText,
    Paste,
    Find,
    Replace,

    SetParagraph = 0x1201,
    SetHeading1,
    SetHeading2,
    SetHeading3,
    SetHeading4,
    SetHeading5,
    SetHeading6,
    PromoteHeading = 0x1210,
    DemoteHeading,
    ToggleBold,
    ToggleItalic,
    ToggleUnderline,
    ToggleStrike,
    ToggleInlineCode,
    InsertLink,
    InsertImage,
    InsertImageFromUrl,
    RotateImageClockwise,
    ToggleQuote,
    ToggleCodeBlock,
    ToggleBulletList,
    ToggleOrderedList,
    InsertHorizontalRule,
    ToggleTaskList,
    InsertTable,
    AddTableRowBefore,
    AddTableRowAfter,
    DeleteTableRow,
    AddTableColumnBefore,
    AddTableColumnAfter,
    DeleteTableColumn,
    AlignTableLeft,
    AlignTableCenter,
    AlignTableRight,
    DeleteTable,
    InsertLineBefore = 0x122C,
    InsertLineAfter,
    InsertMathInline,
    InsertMathBlock,

    ToggleSidebar = 0x1301,
    ViewTree = 0x1302,
    ViewList = 0x1304,
    ShowStatusBar = 0x1303,
    ToggleSourceMode = 0x1305,
    SwitchToWorkspace = 0x1306,
    SwitchToOutline = 0x1307,
    ToggleFocusMode = 0x1308,
    SelectAll = 0x1309,
    ExitCode = 0x130A,
    EditMath = 0x130B,
    ConvertMath = 0x130C,
    DeleteMath = 0x130D,
    ChangeImage = 0x130E,
    ResizeImage100 = 0x130F,
    ResizeImage50 = 0x1310,
    ResizeImage75 = 0x1311,
    ResizeImage90 = 0x1312,
    SaveImageAs = 0x1313,
    ClearFormat = 0x1314,
    FormatPainter = 0x1315,

    ShowShortcuts = 0x1401,
    ShowPreferences,
    ShowAbout,
    ShowChangelog,
    OpenThemeFolder,
    AddTheme,
    ZoomIn,
    ZoomOut,
    ZoomReset,
    FollowSystemColorMode,
}

public readonly record struct CommandState(bool IsEnabled, bool IsChecked = false);

public readonly record struct CommandContext(
    bool DocumentAvailable,
    bool EditorReady,
    bool CanUndo,
    bool CanRedo,
    bool HasSelection,
    bool SidebarVisible,
    bool FocusMode,
    bool SourceMode,
    bool IsPlainText = false,
    bool OutlineActive = false,
    bool ParagraphActive = false,
    int? HeadingLevel = null,
    bool BoldActive = false,
    bool ItalicActive = false,
    bool UnderlineActive = false,
    bool StrikeActive = false,
    bool InlineCodeActive = false,
    bool LinkActive = false,
    bool QuoteActive = false,
    bool CodeBlockActive = false,
    bool BulletListActive = false,
    bool OrderedListActive = false,
    bool TaskListActive = false,
    bool InTable = false,
    string? TableAlign = null,
    bool ImageSelected = false,
    bool CanStartFormatPainter = false,
    bool FormatPainterArmed = false,
    bool DocumentSaved = false,
    bool StatusBarVisible = true,
    bool FollowSystemColorMode = false);
