namespace MarkLeaf.Commands;

public enum AppCommand
{
    NewDocument = 0x1001,
    OpenDocument,
    OpenFolder,
    SaveDocument,
    SaveDocumentAs,
    ExportDocument,
    CleanUnreferencedAssets,
    Exit,

    Undo = 0x1101,
    Redo,
    Cut,
    Copy,
    Paste,
    Find,
    Replace,

    SetParagraph = 0x1201,
    SetHeading1,
    SetHeading2,
    SetHeading3,
    SetHeading4,
    SetHeading5,
    SetHeading6,
    ToggleBold,
    ToggleItalic,
    InsertLink,
    InsertImage,
    RotateImageClockwise,
    ToggleQuote,
    ToggleCodeBlock,
    ToggleBulletList,
    ToggleOrderedList,
    InsertHorizontalRule,
    ToggleTaskList,
    InsertTable,
    AddTableRowBefore,
    AddTableRowAfter,
    DeleteTableRow,
    AddTableColumnBefore,
    AddTableColumnAfter,
    DeleteTableColumn,
    AlignTableLeft,
    AlignTableCenter,
    AlignTableRight,
    DeleteTable,

    ToggleWorkspace = 0x1301,
    ToggleOutline,
    ToggleFocusMode,
    ToggleSourceMode,

    ShowShortcuts = 0x1401,
    ShowAbout,
}

public readonly record struct CommandState(bool IsEnabled, bool IsChecked = false);

public readonly record struct CommandContext(
    bool DocumentAvailable,
    bool EditorReady,
    bool CanUndo,
    bool CanRedo,
    bool HasSelection,
    bool WorkspaceVisible,
    bool OutlineVisible,
    bool FocusMode,
    bool SourceMode,
    bool ParagraphActive = false,
    int? HeadingLevel = null,
    bool BoldActive = false,
    bool ItalicActive = false,
    bool LinkActive = false,
    bool QuoteActive = false,
    bool CodeBlockActive = false,
    bool BulletListActive = false,
    bool OrderedListActive = false,
    bool TaskListActive = false,
    bool InTable = false,
    string? TableAlign = null,
    bool ImageSelected = false,
    bool DocumentSaved = false);
