namespace MarkLeaf.Commands;

public enum AppCommand
{
    NewDocument = 0x1001,
    OpenDocument,
    OpenFolder,
    CloseFolder,
    SaveDocument,
    SaveDocumentAs,
    ExportDocument,
    Exit,
    OpenRecentWorkspace1,
    OpenRecentWorkspace2,
    OpenRecentWorkspace3,
    OpenRecentWorkspace4,
    OpenRecentWorkspace5,
    OpenRecentWorkspace6,
    OpenRecentWorkspace7,
    OpenRecentWorkspace8,

    Undo = 0x1101,
    Redo,
    Cut,
    Copy,
    Paste,
    Find,
    Replace,

    SetParagraph = 0x1201,
    SetHeading1,
    SetHeading2,
    SetHeading3,
    SetHeading4,
    SetHeading5,
    SetHeading6,
    ToggleBold,
    ToggleItalic,
    InsertLink,
    InsertImage,
    RotateImageClockwise,
    ToggleQuote,
    ToggleCodeBlock,
    ToggleBulletList,
    ToggleOrderedList,
    InsertHorizontalRule,
    ToggleTaskList,
    InsertTable,
    AddTableRowBefore,
    AddTableRowAfter,
    DeleteTableRow,
    AddTableColumnBefore,
    AddTableColumnAfter,
    DeleteTableColumn,
    AlignTableLeft,
    AlignTableCenter,
    AlignTableRight,
    DeleteTable,

    ToggleSidebar = 0x1301,
    ToggleFocusMode = 0x1303,
    ToggleSourceMode,

    ShowShortcuts = 0x1401,
    ShowAbout,
}

public readonly record struct CommandState(bool IsEnabled, bool IsChecked = false);

public readonly record struct CommandContext(
    bool DocumentAvailable,
    bool EditorReady,
    bool CanUndo,
    bool CanRedo,
    bool HasSelection,
    bool SidebarVisible,
    bool FocusMode,
    bool SourceMode,
    bool ParagraphActive = false,
    int? HeadingLevel = null,
    bool BoldActive = false,
    bool ItalicActive = false,
    bool LinkActive = false,
    bool QuoteActive = false,
    bool CodeBlockActive = false,
    bool BulletListActive = false,
    bool OrderedListActive = false,
    bool TaskListActive = false,
    bool InTable = false,
    string? TableAlign = null,
    bool ImageSelected = false,
    bool DocumentSaved = false);
